services:
  isaaclab:
    image: stickyburn/isaac-pod:latest
    container_name: isaaclab
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WANDB_API_KEY=${WANDB_API_KEY:-}
      - PUBLIC_KEY=${PUBLIC_KEY:-}
    ports:
      - "2222:22"    # SSH
      - "6901:6901"  # noVNC
    volumes:
      - isaac-storage:/workspace/storage
      - isaac-data:/workspace/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    shm_size: 15gb
    stdin_open: true
    tty: true

volumes:
  isaac-storage:
  isaac-data:
